### ISSUE TITLE
Monri SDK throws an exception when payment is rejected

### ISSUE THREAD

**Issue by abdurahmanadilovic** [MonriPayments/flutter-monri-android-ios#13]
In the test environment price of a 100 will cause the test card to be rejected, but it's not handled by the SDK, here is the stack trace

```
flutter: {data: declined, status: declined}
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Map<dynamic, dynamic>'
#0      new PaymentResponse.fromJson (package:MonriPayments/src/payment_response.dart:17:66)
#1      _MonriPaymentsImpl.confirmPayment (package:MonriPayments/src/monri_payments.dart:131:28)
<asynchronous suspension>
```

`data` exists but the value is a String "declined" and it's not a Map. The SDK tries to cast the string as a Map

**Comment by jasminsuljic** [comment]
Thanks for reported issue, we will take a look in next few days. @harunk-monri - just a ping :)
